email.username=johnybravo89gm@gmail.com
email.password=soeumddidjuklpxm
email.from=johnybravo89gm@gmail.com
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.trust=smtp.gmail.com